### ISSUE TITLE
Build fails under GCC

### ISSUE THREAD

**Issue by zordtk** [redcode/Zeta#3]
I'm trying to use your Z80 emulation core and building fails with the following:

`/usr/local/include/Z/inspection/compiler/modules/GCC.h:552:18: error: missing binary operator before token "("
 #if __has_builtin(__builtin_huge_valf)
                  ^
/usr/local/include/Z/inspection/compiler/modules/GCC.h:554:20: error: missing binary operator before token "("
 #elif __has_builtin(__builtin_inff)
                    ^
/usr/local/include/Z/inspection/compiler/modules/GCC.h:558:18: error: missing binary operator before token "("
 #if __has_builtin(__builtin_nanf)
`
... Cut out the rest of the errors

GCC doesn't seem to support __has_builtin using v8.3.0. Everything builds fine with Clang which does support __has_builtin

**Comment by redcode** [comment]
Yes, that's because GCC support in Z in not finished. You can help if you want working on the GCC module located in `API/Z/inspection/compiler/modules/GCC.h`

**Comment by redcode** [comment]
I think this will be fully fixed around October/November, once I release Z v1.0.

**Comment by donpdonp** [comment]
this is particularly confusing because the Makefile chooses gcc
```
ifndef CC
  CC = gcc
endif
```

It would be helpful if the Z or Z80 INSTALL said something about using clang, which does seem to work.

```
$ make CC=clang
==== Building Z80 (release-dynamic) ====
Z80.c
In file included from ../sources/Z80.c:22:
In file included from ../API/Z/macros/value.h:11:
In file included from ../API/Z/types/base.h:11:
In file included from ../API/Z/inspection/CPU.h:14:
In file included from ../API/Z/inspection/compiler.h:18:
../API/Z/inspection/compiler/modules/Clang.h:1028:34: warning: unknown warning group '-Wextended-offsetof', ignored [-Wunknown-warning-option]
#pragma clang diagnostic ignored "-Wextended-offsetof"
                                 ^
1 warning generated.
Linking Z80

```

**Comment by redcode** [comment]
As I've said, Z is WIP (work in progress), so for now, it only works with Clang. I'm working hard to have a stable official release of Z in late 2019 with full GCC and Visual C++ support.

The Z80 lib depends on Z, but the premake4.lua file is generic, as if Z were finished.

I'm sorry for the inconvenience.

You have 2 otions:

A) Use Clang until a stable version Z is released.
B) Provide your own `Z80-dependencies.h` header predefining the `CPU_Z80_DEPENDENCIES_H` macro.

An example of the option B can be found here: [https://github.com/simonowen/tilemap/blob/master/Z80-support.h](url)

**Comment by redcode** [comment]
BTW, the offsetof warning on Clang is fixed already, but the code is not uploaded. I'm making big changes in Z.

**Comment by donpdonp** [comment]
okay thanks for all your effort, lack of gcc support (for now) is no problem at all. its that the docs never say gcc is not supported. The only indicaiton that gcc is not supported is a rather confusing error message about a C Preprocessor macro. If the README would say that clang is required, I think that would help people who come across the project in the future.

**Comment by redcode** [comment]
Thanks for the suggestion, I'll update the README soon to inform ppl about that.

**Comment by EnricoTrudu** [comment]
Thanks for your work on Z and Z80 that I'm using for an emulator of a Z80 machine, for the purpouse of rewriting the stock firmware. Anyway, switching from OpenBSD to Kubuntu (and gcc) I made a patch on Z that seems to be working for building the Z80 dynamic libs.
Something very trivial like:

#if defined __has_builtin
...your #if __has_builtin(__something)
#endif

I don't know which is the side effect of this kind of patch. Just works for me.
Thanks a lot

**Comment by redcode** [comment]
> Thanks for your work on Z and Z80 that I'm using for an emulator of a Z80 machine, for the purpouse of rewriting the stock firmware. Anyway, switching from OpenBSD to Kubuntu (and gcc) I made a patch on Z that seems to be working for building the Z80 dynamic libs. Something very trivial like:
> 
> #if defined __has_builtin ...your #if __has_builtin(__something) #endif
> 
> I don't know which is the side effect of this kind of patch. Just works for me. Thanks a lot
> 
> P.S. I have a fork with the patched GCC.h.

I'm sorry for not responding sooner, but in all this time I didn't realize that you had posted on this issue.

During this time I have made changes. A friend of mine has built the Z80 library on many operating systems, including OpenBSD. The problem you mention should have been fixed.

I would appreciate it if you could try again.

I have also updated the Z80 library, it now uses CMake as the build system.
